name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute atsAnalysis.ipynb --output atsAnalysis_run.ipynb

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add atsAnalysis_run.ipynb
        git commit -m 'Run notebook and save output'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
